# Generated by Django 3.2.4 on 2023-11-17 06:47

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.IntegerField(blank=True, default=course.models.current_year),
        ),
    ]
