# Generated by Django 3.2.4 on 2023-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='type_coures',
        ),
        migrations.AddField(
            model_name='course',
            name='type_course',
            field=models.CharField(choices=[('self', 'self-paced'), ('instructor', 'instructor-paced')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_overview',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='effort',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='lang',
            field=models.CharField(choices=[('en', 'english'), ('id', 'indonesia')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('basic', 'basic'), ('medium', 'medium'), ('advanced', 'advanced')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_score_to_pas',
            field=models.IntegerField(default=None, verbose_name='required score in %'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('qurations', 'qurations'), ('publish', 'publish'), ('pending', 'pending')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=None, help_text='durations of the quiz in minutes'),
        ),
    ]
