# Generated by Django 3.2.4 on 2023-11-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20231117_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='status',
            new_name='status_course',
        ),
    ]
