# Generated by Django 3.2.4 on 2023-11-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_status_course_status_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='org',
            new_name='org_partner',
        ),
    ]
