# Generated by Django 3.2.4 on 2023-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20231117_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('basic', 'basic'), ('medium', 'medium'), ('advanced', 'advanced')], default='basic', max_length=10, null=True),
        ),
    ]
