# Generated by Django 3.2.4 on 2023-11-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_course_id_section_course_section_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='course_section_id',
            new_name='section_id_course',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='course_section',
            new_name='section_name',
        ),
    ]
