# Generated by Django 3.2.4 on 2023-11-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20231120_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_id_course',
        ),
    ]
