# Generated by Django 3.2.4 on 2023-11-20 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_section_section_id_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_id_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
