# Generated by Django 3.2.4 on 2023-11-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_section_section_id_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='course.course'),
        ),
    ]
