# Generated by Django 3.2.4 on 2023-11-27 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_subsection_sub_id_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='sub_section_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='course.section'),
            preserve_default=False,
        ),
    ]
