# Generated by Django 3.2.4 on 2023-11-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_rename_sub_id_course_subsection_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='sub_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_id', to='course.section'),
        ),
    ]
