# Generated by Django 4.2.7 on 2023-12-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_category_mk_alter_section_section_id_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='sub_section_id',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SubSection',
        ),
    ]
