# Generated by Django 4.1.7 on 2023-11-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.TextField(max_length=191)),
                ('partner_abbreviation', models.TextField(max_length=50)),
                ('partner_email', models.TextField(max_length=500, null=True)),
                ('partner_phone', models.TextField(max_length=50)),
                ('partner_address', models.TextField(max_length=50)),
                ('partner_tax', models.TextField(max_length=50)),
                ('partner_status', models.TextField(max_length=50)),
                ('partner_check', models.TextField(max_length=50)),
            ],
        ),
    ]
