# Generated by Django 4.1.7 on 2023-11-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Partner',
        ),
    ]
