# Generated by Django 4.1.7 on 2023-11-14 08:56

from django.db import migrations, models
import partner.models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_rename_item_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_logo',
            field=models.ImageField(blank=True, null=True, upload_to=partner.models.filepath),
        ),
    ]
