# Generated by Django 4.1.7 on 2023-11-15 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partner_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_join',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
