# Generated by Django 4.1.7 on 2023-11-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_partner_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Displayusername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
