# Generated by Django 4.1.7 on 2023-11-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_displayusername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Displayusername',
        ),
    ]
