# Generated by Django 4.1.7 on 2023-11-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_partner_partner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_email',
        ),
    ]
