# Generated by Django 4.1.7 on 2023-11-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0008_remove_partner_partner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_add', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
