# Generated by Django 3.2.4 on 2023-11-17 06:47

from django.db import migrations, models
import partner.models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20231117_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=models.ImageField(blank=True, null=True, upload_to=partner.models.filepath),
        ),
    ]
