# Generated by Django 3.2.4 on 2023-11-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_alter_partner_partner_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qourse_overview',
        ),
    ]
