# Generated by Django 3.2.4 on 2023-11-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_delete_qourse_overview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_email',
            new_name='partner_email_id',
        ),
    ]
