# Generated by Django 3.2.4 on 2023-11-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_rename_partner_email_partner_partner_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_email_id',
            new_name='partner_email',
        ),
    ]
