# Generated by Django 5.0.6 on 2024-06-11 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_rename_partner_email_id_partner_partner_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_add', to=settings.AUTH_USER_MODEL),
        ),
    ]
