# Generated by Django 5.0.6 on 2024-06-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_alter_partner_partner_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_abbreviation',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_check',
            new_name='checks',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_join',
            new_name='join',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_tax',
            new_name='tax',
        ),
    ]
