# Generated by Django 5.0.6 on 2024-06-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0019_alter_partner_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='email',
            new_name='e_mail',
        ),
    ]
