# Generated by Django 5.0.6 on 2024-06-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0020_rename_email_partner_e_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='name',
            new_name='partner_name',
        ),
    ]
