# Generated by Django 5.0.6 on 2024-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0021_rename_name_partner_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='checks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax',
            field=models.CharField(max_length=50),
        ),
    ]
